export const GET_CONTACTS_LIST_SUCCEED = "GET_CONTACTS_LIST_SUCCEED";

export const HANDLE_CREATE_CONTACT_SUCCEED = "HANDLE_CREATE_CONTACT_SUCCEED";

export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";
