export const GET_CUSTOMERS_LIST_SUCCEED = "GET_CUSTOMERS_LIST_SUCCEED";

export const OPEN_CREATE_PAY_ACC_DIALOG_CONFIRM =
  "OPEN_CREATE_PAY_ACC_DIALOG_CONFIRM";

export const CLOSE_CREATE_PAY_ACC_DIALOG_CONFIRM =
  "CLOSE_CREATE_PAY_ACC_DIALOG_CONFIRM";

export const HANDLE_CREATE_PAY_ACC_SUCCEED = "HANDLE_CREATE_PAY_ACC_SUCCEED";

export const HANDLE_CREATE_PAY_ACC_ERROR = "HANDLE_CREATE_PAY_ACC_ERROR";

export const CLOSE_CREATE_PAY_ACC_DIALOG_OPERATED =
  "CLOSE_CREATE_PAY_ACC_DIALOG_OPERATED";
