export const CLOSE_MESSAGE = "CLOSE_MESSAGE";

export const GET_PAY_ACCS_LITS_SUCCEED = "GET_PAY_ACCS_LITS_SUCCEED";

export const OPEN_CLOSE_PAY_ACC_DIALOG = "OPEN_CLOSE_PAY_ACC_DIALOG";

export const CLOSE_CLOSE_PAY_ACC_DIALOG = "CLOSE_CLOSE_PAY_ACC_DIALOG";

export const HANDLE_INPUT_CHANGE = "HANDLE_INPUT_CHANGE";

export const HANDLE_CLOSE_PAY_ACC_SUCCEED = "HANDLE_CLOSE_PAY_ACC_SUCCEED";

export const OPEN_VIEW_HISTORY_DIALOG = "OPEN_VIEW_HISTORY_DIALOG";
