export const GET_PAY_ACCS_LIST_SUCCEED = "GET_PAY_ACCS_LIST_SUCCEED";

export const OPEN_PAY_IN_PANEL = "OPEN_PAY_IN_PANEL";

export const CLOSE_PAY_IN_PANEL = "CLOSE_PAY_IN_PANEL";

export const HANDLE_PAY_IN_SUCCEED = "HANDLE_PAY_IN_SUCCEED";
